version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"

    labels:
      - "dependencies"
      - "backend"

    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

    labels:
      - "dependencies"
      - "frontend"

    open-pull-requests-limit: 5