apply plugin: "checkstyle"


System.setProperty("config_loc", "${rootDir}/config/checkstyle")

checkstyle {
    checkstyle {
        toolVersion '10.20.2'
        configFile = file("${rootDir}/config/checkstyle/google_checkstyle.xml")
        ignoreFailures = false
        maxWarnings = 0
    }

    checkstyleMain {
        source = 'src/main/java'
    }

    checkstyleTest {
        source = 'src/test/java'
    }
}