spring:
  application:
    name: software
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/srmartdb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
